#Layout for this config file is as follows
#
#Enabled: <True/False>
#TimeBetweenRewards: <Days>:<Hours>:<Minutes>
#AutomaticCollection: <true/false>
#ShowTime: <true/false>
#ShowRewards: <true/false>
#Messages:
#   rewardsReady: <Message to send when players receive/have rewards to collect>
#   unableToGiveRewards: <Message to send when players haven't gotten all of their items>
#   noRewards: <Message to send when players have used the /receive command and there are no rewards for them to collect>
#   noPermission: <Message to send when players do not have permission>
#Rewards:
# - level: <PowerLevel player must be at to receive rewards>
#   rewards: <Data Value> <Quantity> 
#	money: <amount>
#	enchantments: <item> <enchantment>:<level> <enchantment>:<level> ... <item> <enchantment>:<level> ... ...
# - level: <A higher PowerLevel>
#   money: <amount>
#   enchantments: <tool/weapon/armour> <enchantment ID>:<enchantment level>
#   time: <Sets a new time between each reward for this level>
#
#Example layout
#
#Enabled: True #if false players will no longer receive rewards
#TimeBetweenRewards: 1:12:0 #Rewards will be given every 1 day and 12 hours
#AutomaticCollection: false #Players will have to use the /receive command to get their rewards
#ShowTime: true #Players will see the time they have to wait till their next rewards when using the command /listRewards
#ShowRewards: false #Players will not be told what they just receive. Set to true if you want players to get a message telling them what their reward was.
#Messages:
#   rewardsReady: You have rewards to collect. Use /receive to get them!
#   unableToGiveRewards: Your inventory is full. Use /receive when your inventory isn't full to receive the rest of your rewards.
#   noRewards: Looks like you've already collected your rewards.
#   noPermission: Sorry, but you do not have permission to use this command.
#Rewards:
# - level: 0
#   rewards: wool:4 2 #2x yellow wool
#	money: 10.01 #Player will get 10.01 of your servers currency
# - level: 5
#   rewards: 37 1 #1x yellow flower
# - level: 10
#   rewards: 273 1 stone_axe 1 #1x stone shovel, 1x stone axe
#	enchantments: 306 0:5 PROTECTION_FIRE:1 #Iron helmet with protection against the environment and fire at levels 5 and 1 respectively
# - level: 20
#   rewards: 282 1 leather_helmet 1 leather_boots 1 #1x mushroom stew, 1x leather helmet, 1x leather boots
#	money: 200 #Player will get 200 of your servers currency
# - level: 25
#   money: between 200.25 400 #Player will get between 200 and 400 of your servers money
# - level: 30
#   rewards: 47 10 or 84 1 #Player will randomly get either 10 bookshelves or 1 jukebox (both with equal chances)
# - level: 40
#   rewards: random or diamond #Player will either get a diamond or a completely random item
#   time: 2:0:0 #The player will have to wait 2 days between rewards
#
#The levels should be in order, from smallest to biggest.
#A player with a power level of 7 will get the level 5 rewards,
#in this case a yellow flower. The player will NOT get the level 0
#rewards.
#
#Rewards, Messages, AutomaticCollection, ShowTime and ShowRewards are optional
#Enabled and TimeBetweenRewards are required.
#Of the Rewards tag, the level tag is required, 
#but all other tags are optional.
#
#The reward tag has two different "random" features.
#The first is that players will randomly be given predefined sets of rewards.
#The usage for this is as follows:
#   rewards: <Data value> <Quantity> ... or <Data value> <Quantity> ... or ...
#The "or" word is used to separate different sets, and the players will randomly be given one of the sets.
#The second random feature will give players a random amount (up to 64) of any item.
#It is used like this:
#   rewards: random
#Be careful as this can give players any items (including sponges, chain-mail, portal blocks etc)
#The two random features can be combined.
#   rewards: <Data value> <Quantity> ... or random or <Data value> <Quantity> ...
#
#Messages support chat colours using the & character followed by 0-9 or e-f.
#If you find the message isn't showing correctly surround it with the '' characters.
#
# ------------ Enchantment IDs ------------
# Name                     - MaxLevel - ID
# PROTECTION_ENVIRONMENTAL - 4        - 0
# PROTECTION_FIRE          - 4        - 1
# PROTECTION_FALL          - 4        - 2
# PROTECTION_EXPLOSIONS    - 4        - 3
# PROTECTION_PROJECTILE    - 4        - 4
# OXYGEN                   - 3        - 5
# WATER_WORKER             - 1        - 6
# DAMAGE_ALL               - 5        - 16
# DAMAGE_UNDEAD            - 5        - 17
# DAMAGE_ARTHROPODS        - 5        - 18
# KNOCKBACK                - 2        - 19
# FIRE_ASPECT              - 2        - 20
# LOOT_BONUS_MOBS          - 3        - 21
# DIG_SPEED                - 5        - 32
# SILK_TOUCH               - 1        - 33
# DURABILITY               - 3        - 34
# LOOT_BONUS_BLOCKS        - 3        - 35
# ARROW_DAMAGE             - 5        - 48
# ARROW_KNOCKBACK          - 2        - 49
# ARROW_FIRE               - 1        - 50
# ARROW_INFINITE           - 1        - 51

Enabled: True
TimeBetweenRewards: 1:0:0
AutomaticCollection: false
ShowRewards: false
ShowTime: true
Messages:
   rewardsReady: You have rewards ready for collection!
   unableToGiveRewards: Unable to give you all of your rewards
   noRewards: You currently do not have any rewards to collect
   noPermission: You do not have permission to use this command
Rewards:
 - level: 0
   rewards: 263 1 
   money: 200
 - level: 1
   rewards: 265 5 263 21
 - level: 2
   rewards: 266 1
 - level: 4
   enchantments: 276 16:5 19:5 274 34:5