name: mcReward
main: com.github.no2665.McReward.McRewardPlugin
version: 1.4
commands:
   addReward:
      description: Add a rewards to a new or existing set of rewards
      permissions: editConfigPerms
      usage: /addReward <level> <Data Value> <quantity> ...
   deleteReward:
      description: Delete a whole set of rewards
      permissions: editConfigPerms
      usage: /deleteReward <level>
   receive:
      description: Receive your rewards
      permissions: receiveRewards
      aliases: receiveRewards
   listRewards:
      description: See the rewards that you can get.
      permissions: receiveRewards
      
permissions:
   editConfigPerms:
      description: Allows you to edit the config file from commands
      default: op
   receiveRewards:
      description: Allows players to receive rewards.
      default: true