name: mcReward
main: com.github.no2665.McReward.McRewardPlugin
version: 0.1
commands:
   addReward:
      description: Add a rewards to a new or existing set of rewards
      permissions: editConfigPerms
      usage: /addReward <level> <Data Value> <quantity> ...
   deleteReward:
      description: Delete a whole set of rewards
      permissions: editConfigPerms
      usage: /deleteReward <level>
    
permissions:
   editConfigPerms:
      description: Allows you to edit the config file from commands
      default: op